name: Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - 'public/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  deploy:
    name: Build & Deploy Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CLI repo
        uses: actions/checkout@v6.0.2

      - uses: pnpm/action-setup@v4.2.0
        with:
          version: '10'

      - uses: actions/setup-node@v6.2.0
        with:
          node-version: '22'

      - name: Get pnpm store directory
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4.2.2
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-docs-${{ hashFiles('public/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-docs-

      - name: Install docs dependencies
        working-directory: public
        run: pnpm install --frozen-lockfile

      - name: Build docs
        working-directory: public
        run: pnpm build

      - name: Add CNAME
        run: echo "docs.cli.prokodo.com" > public/build/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/build
